wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744906074
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 14
      - 23
      - 24
      - 37
      4: 3.11.11
      5: 0.19.9
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.0008809492437079923
loss_function:
  desc: null
  value: focal
num_epochs:
  desc: null
  value: 20
optimizer:
  desc: null
  value: rmsprop
